name: Go with GolangCI-Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v2.1
  EXCLUDED_BUILD_MODULES: "./pkg|./shared"
  MODULES: "./pkg ./shared ./menu-service ./order-service ./kitchen-service ./payment-service ./table-service"

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
      ignore-modules: ${{ steps.set-ignore-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure Workspace and Install Dependencies
        run: |
          go work init
          go work use ${{ env.MODULES }}

      - id: set-modules
        run:
          echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

      - id: set-ignore-modules
        run:
          echo "modules=$(go list -m -json all | jq -s '[.[] | select(.Dir | test("shared|pkg") | not) | .Dir]' -c)" >> $GITHUB_OUTPUT

  golangci-lint:
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Configure Workspace and Install Dependencies
        run: |
          go work init
          go work use ${{ env.MODULES }}
          cd ${{ matrix.modules }} && go mod tidy && go mod download

      - name: golangci-lint ${{ matrix.modules }}
        uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.modules }}

  test:
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules.outputs.ignore-modules) }}
    outputs:
      modules: ${{ needs.detect-modules.outputs.ignore-modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure Workspace and Install Dependencies
        run: |
          go work init
          go work use ${{ env.MODULES }}
          cd ${{ matrix.modules }} && go mod tidy && go mod download

      - name: Run Tests
        run: |
          cd ${{ matrix.modules }}
          go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: [ golangci-lint, test ]
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.test.outputs.modules) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure Workspace and Install Dependencies
        run: |
          go work init
          go work use ${{ env.MODULES }}
          cd ${{ matrix.modules }} && go mod tidy && go mod download

      - name: Build
        run: |
          cd ${{ matrix.modules }}
          go build -o app cmd/main.go