name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.3

      - name: Configure Workspace and Install Dependencies
        run: |
          go work init
          go work use ./pkg ./shared ./menu-service ./order-service ./kitchen-service ./payment-service ./table-service
          if [ -d ./menu-service ]; then cd ./menu-service && go mod tidy && go mod download && cd ..; fi
          if [ -d ./kitchen-service ]; then cd ./kitchen-service && go mod tidy && go mod download && cd ..; fi
          if [ -d ./payment-service ]; then cd ./payment-service && go mod tidy && go mod download && cd ..; fi
          if [ -d ./table-service ]; then cd ./table-service && go mod tidy && go mod download && cd ..; fi
          if [ -d ./order-service ]; then cd ./order-service && go mod tidy && go mod download && cd ..; fi

      - name: Build Menu Service
        working-directory: ./menu-service
        run: go build -o app cmd/main.go

      - name: Build Kitchen Service
        working-directory: ./kitchen-service
        run: go build -o app cmd/main.go

      - name: Build Payment Service
        working-directory: ./payment-service
        run: go build -o app cmd/main.go

      - name: Build Table Service
        working-directory: ./table-service
        run: go build -o app cmd/main.go

      - name: Build Order Service
        working-directory: ./order-service
        run: go build -o app cmd/main.go

      - name: Run Tests for Menu Service
        working-directory: ./menu-service
        run: go test -v ./...

      - name: Run Tests for Kitchen Service
        working-directory: ./kitchen-service
        run: go test -v ./...

      - name: Run Tests for Payment Service
        working-directory: ./payment-service
        run: go test -v ./...

      - name: Run Tests for Table Service
        working-directory: ./table-service
        run: go test -v ./...

      - name: Run Tests for Order Service
        working-directory: ./order-service
        run: go test -v ./...